apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-project
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-project
  template:
    metadata:
      labels:
        app: test-project
    spec:
      containers:
      - image: registry.gitlab.com/mathieu.chauvet.adaztech/test-project:master-90031ad20de31fd8530b0ebf03f79d1bc8ae2753
        name: test-project
        ports:
        - containerPort: 8080
      imagePullSecrets: 
      - name: registry-credentials